include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - windows/**
    - linux/**
    - test/**
  language:
    strict-casts: true
    strict-inference: true
  errors:
    deprecated_member_use: ignore
    sort_constructors_first: ignore
    directives_ordering: ignore
    avoid_slow_async_io: ignore
    unintended_html_in_doc_comment: ignore
    unnecessary_import: ignore
    unnecessary_this: ignore
    prefer_function_declarations_over_variables: ignore

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unnecessary_statements
